### PR TITLE
Update imgui to 1.72b

### PR DESCRIPTION
**Pull request by sweetkristas**

### CODE REVIEW

**Comment by galegosimpatico** [comment]
Is there a checklist of remaining things for this, or something?

**Comment by DDR0** [comment]
What changes were made to anura.vcxproj? I made some a few days ago to skip a few libraries we weren't using, like Box2D.

**Comment by galegosimpatico** [comment]
> What changes were made to anura.vcxproj? I made some a few days ago to skip a few libraries we weren't using, like Box2D.

There are only 44 changes: 29 additions and 15 deletions.

**Comment by DDR0** [comment]
Diffview wasn't being very helpful, so I just merged the longer one with the if statement in it.

**Comment by DDR0** [comment]
Hm, I evidently did that workflow wrong. I've [reverted my merge into master](f2af5cf4b03f95af28083603750fcb1ecf37f925), because it threw a lot of errors at me on Linux. I should have checked out the branch and tested it there. Something for next time, I guess.

Here are the errors blocking me on Ubuntu: https://gist.github.com/DDR0/7f347a9c596f6bb6ad6f29390f35fb78

**Comment by galegosimpatico** [comment]
simplify your life by checking stuff [before mergning][0] instead of after. When possible, have others do those checks for you. Consider also using bots too

[0]: https://github.com/anura-engine/anura/pull/288#issuecomment-667288287

**Comment by DDR0** [comment]
Aye, having a build server would be nice.

**Pull request merged**
