### PR TITLE
typos

### PR DESCRIPTION
**Pull request by a-detiste**
typo found by Debian's lintian

### CODE REVIEW

**Review by DDR0 — APPROVED** [review]
Small but solid changes. 👌

**Comment by DDR0** [comment]
Thank you for the tidying up, @a-detiste. o7

**Comment by Rotonen** [comment]
I've discovered a fault in my CI setup with regards to builds from forks: turns out only pull_request triggers from forks can fire, not push triggers.

https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull-request-events-for-forked-repositories

This now needs to go first: https://github.com/anura-engine/anura/pull/380

And then one can simply click the "update branch" button on this branch and reapprove and the automerge and merge queue machinery will take care of the rest.

Sorry for the inconvenience.

**Comment by a-detiste** [comment]
I plan to package this for Debian at the event that's happening end of this week in Cambridge. (FWIW) then we can update Frogatto.

**Comment by Rotonen** [comment]
Please coordinate all things Debian with Martin Quinson as he seems to be the currently active uploader for the frogatto package.

**Comment by a-detiste** [comment]
I never received the message that is publicly archived here: https://bugs.debian.org/1055343

I know now it's being handled, thanks for the tip.

**Pull request merged**
