### PR TITLE
Clear untracked imgui docs after building Anura.

### PR DESCRIPTION
**Pull request by ghost**
I'm probably missing some of the submodule internals, sorry if the case.

After building Anura, the `imgui.d`, `imgui.o`, `imgui_draw.d` and `imgui_draw.o` docs are being created, so making dirty the ImGui detached head at https://github.com/sweetkristas/imgui/commit/beb0ea7b47a4620c62253d5193ead0af120ec3ba with uncommited changes, and so making dirty Anura with uncommitted changes.

This is an attempt at removing those files, however the new code will only be executed after successful builds, not after each build.

If it had to be executed after each build, I can't think of anything better than a change in `.gitignore` at the submodule. However I'm afraid at the possibility of causing submodule pain to the rest of the users.

### CODE REVIEW

**Comment by DDR0** [comment]
I'd say a .gitignore solution would be fine, but either way works.

**Comment by ghost** [comment]
Maybe... it would be cutest if Anura was depending on `github.com/anura-engine/imgui` at some `anura-trunk` branch, instead of on https://github.com/sweetkristas/imgui at her `master` branch..?

**Comment by ghost** [comment]
Made irrelevant by https://github.com/sweetkristas/imgui/commit/ce5b6146be206194298109d7ff8c71ecac70adf6, https://github.com/sweetkristas/imgui/commit/d7ce9212f1d321a1470c8ab8dceeed222c55a3ce and https://github.com/anura-engine/anura/commit/fa122ab24d7247e4d3b7bc8f55749a3d3c0c6e8e.

**Comment by ghost** [comment]
**If anyone has their local clone complaining of pending changes to apply to the submodule, I suppose they can silence it running `git submodule update`.**

My log around https://github.com/anura-engine/anura/commit/fa122ab24d7247e4d3b7bc8f55749a3d3c0c6e8e:

```
0:183:1519921707:gs@$HOST:$ANURA_BASE$ git status
On branch openbsd                                                            
Your branch is up-to-date with 'bentley/openbsd'.               
Changes not staged for commit:                                          
  (use "git add <file>..." to update what will be committed)     
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
                                                                              
        modified:   imgui (untracked content)                                            
no changes added to commit (use "git add" and/or "git commit -a")      
0:184:1519922816:gs@$HOST:$ANURA_BASE$ cd imgui
[...]
0:196:1519982653:gs@$HOST:$ANURA_BASE/imgui$ git pull
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (2/2), done.
remote: Total 4 (delta 1), reused 3 (delta 1), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/sweetkristas/imgui
   beb0ea7..d7ce921  master     -> origin/master
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

[...]
0:198:1519982672:gs@$HOST:$ANURA_BASE/imgui$ git checkout master && git merge upstream/master
Switched to branch 'master'
Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
  (use "git pull" to update your local branch)
merge: upstream/master - not something we can merge
1:199:1519982691:gs@$HOST:$ANURA_BASE/imgui$ git pull
Updating beb0ea7..d7ce921
Fast-forward
 .gitignore | 3 +++
 1 file changed, 3 insertions(+)
 create mode 100644 .gitignore
0:200:1519982699:gs@$HOST:$ANURA_BASE/imgui$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
0:201:1519982705:gs@$HOST:$ANURA_BASE/imgui$ cd ..
0:202:1519982706:gs@$HOST:$ANURA_BASE$ git status
On branch openbsd
Your branch is up-to-date with 'bentley/openbsd'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   imgui (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
0:203:1519982707:gs@$HOST:$ANURA_BASE$ git checkout trunk
M       imgui
Switched to branch 'trunk'
Your branch is up-to-date with 'origin/trunk'.
[...]
0:229:1519983340:gs@$HOST:$ANURA_BASE$ git status
On branch trunk
Your branch is up-to-date with 'origin/trunk'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   imgui (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
0:230:1519983343:gs@$HOST:$ANURA_BASE$ cd imgui
[...]
0:233:1519983383:gs@$HOST:$ANURA_BASE/imgui$ git status
HEAD detached from beb0ea7
nothing to commit, working tree clean
[...]
0:238:1519983420:gs@$HOST:$ANURA_BASE/imgui$ git checkout master
Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
0:239:1519983427:gs@$HOST:$ANURA_BASE/imgui$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
0:240:1519983429:gs@$HOST:$ANURA_BASE/imgui$ cd ..
0:241:1519983431:gs@$HOST:$ANURA_BASE$ git submodule sync
Synchronizing submodule url for 'imgui'
0:242:1519983435:gs@$HOST:$ANURA_BASE$ cd imgui
0:243:1519983442:gs@$HOST:$ANURA_BASE/imgui$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
0:244:1519983443:gs@$HOST:$ANURA_BASE/imgui$ cd ..
0:245:1519983450:gs@$HOST:$ANURA_BASE$ git submodule udpate
usage: git submodule [--quiet] add [-b <branch>] [-f|--force] [...]
   or: git submodule [--quiet] status [--cached] [--recursive] [...]
   [...]
   or: git submodule [--quiet] sync [--recursive] [--] [<path>...]
1:246:1519983455:gs@$HOST:$ANURA_BASE$ git submodule update
Submodule path 'imgui': checked out 'beb0ea7b47a4620c62253d5193ead0af120ec3ba'
0:247:1519983458:gs@$HOST:$ANURA_BASE$ git status
On branch trunk                         
Your branch is up-to-date with 'origin/trunk'.
Changes not staged for commit:          
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)
                                        
        modified:   imgui (untracked content)
                                        
no changes added to commit (use "git add" and/or "git commit -a")
0:248:1519983522:gs@$HOST:$ANURA_BASE$ cd imgui
0:249:1519983526:gs@$HOST:$ANURA_BASE/imgui$ git status
HEAD detached at beb0ea7                
Untracked files:                        
  (use "git add <file>..." to include in what will be committed)
                                        
        imgui.d                         
        imgui.o                         
        imgui_draw.d                    
        imgui_draw.o                    
                                        
nothing added to commit but untracked files present (use "git add" to track)
0:250:1519983527:gs@$HOST:$ANURA_BASE/imgui$ git checkout master
Previous HEAD position was beb0ea7... Add some conversions from glm vectors to ImGui vectors.
Switched to branch 'master'             
Your branch is up-to-date with 'origin/master'.
0:251:1519983547:gs@$HOST:$ANURA_BASE/imgui$ git status
On branch master                        
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean   
0:252:1519983552:gs@$HOST:$ANURA_BASE/imgui$ git log --pretty="%H" | head -1
d7ce9212f1d321a1470c8ab8dceeed222c55a3ce
[...]
0:255:1519983578:gs@$HOST:$ANURA_BASE/imgui$ git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working tree clean
0:256:1519983624:gs@$HOST:$ANURA_BASE/imgui$ cd ..
0:257:1519983625:gs@$HOST:$ANURA_BASE$ git status
On branch trunk
Your branch is up-to-date with 'origin/trunk'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   imgui (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
0:258:1519983627:gs@$HOST:$ANURA_BASE$ git add imgui
0:259:1519983633:gs@$HOST:$ANURA_BASE$ git status
On branch trunk
Your branch is up-to-date with 'origin/trunk'.
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   imgui

0:260:1519983637:gs@$HOST:$ANURA_BASE$ git diff --cached
diff --git a/imgui b/imgui
index beb0ea7b..d7ce9212 160000
--- a/imgui
+++ b/imgui
@@ -1 +1 @@
-Subproject commit beb0ea7b47a4620c62253d5193ead0af120ec3ba
+Subproject commit d7ce9212f1d321a1470c8ab8dceeed222c55a3ce
0:261:1519983642:gs@$HOST:$ANURA_BASE$ git commit
Aborting commit due to empty commit message.
1:262:1519983670:gs@$HOST:$ANURA_BASE$ git commit -m 'Update submodule.' && git remote -v
[trunk fa122ab2] Update submodule.
 1 file changed, 1 insertion(+), 1 deletion(-)
bentley https://github.com/bentley/anura (fetch)
bentley https://github.com/bentley/anura (push)
origin  https://galegosimpatico@github.com/galegosimpatico/anura (fetch)
origin  https://galegosimpatico@github.com/galegosimpatico/anura (push)
teto    https://github.com/teto/anura/ (fetch)
teto    https://github.com/teto/anura/ (push)
upstream        https://github.com/anura-engine/anura (fetch)
upstream        https://github.com/anura-engine/anura (push)
0:263:1519983732:gs@$HOST:$ANURA_BASE$ git fetch upstream
0:264:1519983753:gs@$HOST:$ANURA_BASE$ git push upstream trunk && git push origin trunk
Username for 'https://github.com': galegosimpatico
Password for 'https://galegosimpatico@github.com':
Counting objects: 2, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 257 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/anura-engine/anura
   de90dccb..fa122ab2  trunk -> trunk
Password for 'https://galegosimpatico@github.com':
Counting objects: 2, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 257 bytes | 0 bytes/s, done.
Total 2 (delta 1), reused 0 (delta 0)
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/galegosimpatico/anura
   de90dccb..fa122ab2  trunk -> trunk
0:265:1519983798:gs@$HOST:$ANURA_BASE$ git submodule update
0:266:1519984279:gs@$HOST:$ANURA_BASE$ cd imgui
0:267:1519984283:gs@$HOST:$ANURA_BASE/imgui$ git checkout be beb0
error: pathspec 'be' did not match any file(s) known to git.
error: pathspec 'beb0' did not match any file(s) known to git.
1:268:1519984291:gs@$HOST:$ANURA_BASE/imgui$ git checkout beb0
Note: checking out 'beb0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at beb0ea7... Add some conversions from glm vectors to ImGui vectors.
0:269:1519984295:gs@$HOST:$ANURA_BASE/imgui$ cd ..
0:270:1519984303:gs@$HOST:$ANURA_BASE$ git stataus
git: 'stataus' is not a git command. See 'git --help'.

Did you mean this?
        status
1:271:1519984305:gs@$HOST:$ANURA_BASE$ git status
On branch trunk
Your branch is up-to-date with 'origin/trunk'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   imgui (new commits, untracked content)

no changes added to commit (use "git add" and/or "git commit -a")
0:272:1519984307:gs@$HOST:$ANURA_BASE$ git submodule update
Submodule path 'imgui': checked out 'd7ce9212f1d321a1470c8ab8dceeed222c55a3ce'
0:273:1519984313:gs@$HOST:$ANURA_BASE$ git status
On branch trunk
Your branch is up-to-date with 'origin/trunk'.
nothing to commit, working tree clean
0:274:1519984314:gs@$HOST:$ANURA_BASE$ _
```

**Pull request closed without merging**
