### PR TITLE
add an option to compile with -fsanitize=address, fix a small leak

### PR DESCRIPTION
**Pull request by cbeck88**

### CODE REVIEW

**Comment by sweetkristas** [comment]
I'm kind of nervous about this, we've had problems on done platforms that try and smartly clean up font handles snd it causes issues on exit (mainly Windows). Which is why we don't bother cleaning them up. Or at least using the OS to do it.

Will that sanitise address thing work on gcc versions 4.7.3 and later?

**Comment by cbeck88** [comment]
hmmm ok

I committed some code to wesnoth a few months ago that does basically exactly this, calling TTF_closefont, and no one on msvc or mingw reported problems. But that was also on SDL ttf 1.2.x, not SDL 2.

The sanitize address thing is supposed to work in clang 3.1+ and gcc 4.8+. I had problems in gcc 4.8+ but it seems to work fine in gcc 5.1. It works well in clang anyways.

One other bonus from this patch is that you can use "make CXX=g++-5" and it will work correctly and pass the right flags to it.

Sanitize address seems to be much, much faster than valgrind is, with anura anyways.

**Comment by sweetkristas** [comment]
Okay, we'll try it and see then.

**Comment by cbeck88** [comment]
I checked actually, I think the "close font" code was in the game forever, I don't think I added it.

https://github.com/wesnoth/wesnoth/commit/b0ed5403fee2be3f979509ff3f1b1dedc3f1bc31#diff-2aaa5ba57b150041a2e74c625a51e663L345

**Pull request merged**
