### PR TITLE
Improve compilation process

### PR DESCRIPTION
**Pull request by teto**
I've started trying to package the engine for nixos and here are a first few changes that can be helpful in general.
firstly use sdl2-config to get include and linker folders for SDL2. Also I believe imgui is a mandatory dependancy but it was not listed in INSTALL.

EDIT: I just noticed imgui is included but as a submodule. cairo is not mentioned htough.

### CODE REVIEW

**Comment by teto** [comment]
Is there any stable version to package ? I did not find any git tag. More specifically I would like to package a version that works both with frogatto and http://argentumage.com/about.html ?

**Comment by ghost** [comment]
Greetings! And thank you for caring.

You may have an answer here, but maybe you could have it faster in the Frogatto & Friends Discord server. See https://frogatto.com/2016/11/21/peep-this/ for more information.

Frogatto stable is, to my understanding, still 1.3.x. You can found tags and branches for it [at the Frogatto repo](https://github.com/frogatto/frogatto/tree/1.3_stable).

Regarding Argentum Age, maybe it's a little bit different because at the moment it is meant to be in continuous roll release with fast iteration. You can join discussion at [the Argentum Age Discord server](https://discord.gg/0s6mSoZ1vJPlvcIw) for discussing the topic of packaging Argentum Age not only with their developers but with players too.

**Comment by teto** [comment]
I finally managed to complete compilation on nixos and would like to provide the package.
Maybe there should a variable with pkg-config compatible libraries so that one can use `pkg-config --libs $libraries` and `pkg-config --cflags $libraries` instead of copy/pasting like I did. I can make the change if requested and squash the commits.

**Comment by davewx7** [comment]
Did you have to build with SDL2_Mixer? It shouldn't be necessary I don't think....

**Comment by teto** [comment]
Indeed it compiles without it. 
I've added a MANDATORY_LIBS variable that contains the libraries for pkg-config to look for.

**Pull request merged**
