### PR TITLE
disable a clang warning, add a unit test for ffl "filter" function

### PR DESCRIPTION
**Pull request by cbeck88**

### CODE REVIEW

**Comment by sweetkristas** [comment]
Given that I went to quite some trouble in the first place to get rid of using that warning, I'd prefer we actually fixed the code rather than disabling more compiler warnings.

**Comment by cbeck88** [comment]
Ok, I'll do that instead

Do you feel similarly about -Wno-parenthesis-equality ? I can't remember when I added that to the clang build.

**Comment by sweetkristas** [comment]
Well ideally I'd like to run with -Wall -Werror, but I can't see that happening in the short term. The less number of compiler warnings we need to suppress the better imo.

**Comment by cbeck88** [comment]
Ok, I fixed the one I was going to disable.

I also rejiggered the make file a little so that USE_LUA can be disabled, and I removed the two clang warnings I suppressed originally so that lua could be compiled. They only get disabled if USE_LUA=yes now.

**Pull request merged**
